default_language_version:
  python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.*\.md$
      - id: end-of-file-fixer
      - id: debug-statements
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: detect-private-key

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.18.0
    hooks:
      - id: markdownlint
        language_version: system

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
